const CommodityList = () => {
        return (
                <div>
                <div className="container main1" style={{ position: "relative", height: "2700px", align: "center", width: "auto"}}>
                        <h4>List of Commodity : </h4>
                       
                        <div style={{ position: "absolute", top: "60px", left: "10px" }}>
                                <table className="table table-border table-striped table-hover"><thead style={{ backgroundColor: "#232F3E", color: "white", }}>
                                        <tr><th colspan="1">FOOD GRAINS/ CEREALS</th></tr></thead><tbody><tr><td>1. Arhar</td></tr><tr><td>2. Arhar Dal Split</td></tr><tr><td>3. Bajra</td></tr><tr><td>4. Barley</td></tr><tr><td>5. Basmati rice</td></tr><tr><td>6. Buck Wheat</td></tr><tr><td>7. Chakhao Or Black Rice</td></tr><tr><td>8. Chana Dal Split</td></tr><tr><td>9. Chana whole</td></tr><tr><td>10. Horse Gram</td></tr><tr><td>11. Jowar </td></tr><tr><td>12. Kabuli Chana Whole</td></tr><tr><td>13. Lobia</td></tr><tr><td>14. Maize</td></tr><tr><td>15. Masoor whole</td></tr><tr><td>16. Moong Dal Split</td></tr><tr><td>17. Moong whole</td></tr><tr><td>18. Moth</td></tr><tr><td>19. Oats Raw</td></tr><tr><td>20. Paddy</td></tr><tr><td>21. Ragi</td></tr><tr><td>22. Rajma</td></tr><tr><td>23. Urad Dal Split</td></tr><tr><td>24. Urad whole</td></tr><tr><td>25. Wheat</td></tr><tr><td>26. White Peas</td></tr></tbody></table><br /><br />

                        </div>
                        <div style={{ position: "absolute", top: "60px", left: "250px" }}>
                                <table className="table table-border table-striped table-hover"><thead style={{ backgroundColor: "#232F3E", color: "white" }}><tr><th colspan="1">OILSEEDS</th></tr></thead><tbody><tr><td> 1. Castor seed</td></tr><tr><td>2. Cotton Seed</td></tr><tr><td>3. Kusum seed</td></tr><tr><td>4. Linseed</td></tr><tr><td>5. Mustard seed</td></tr><tr><td>6. Neem Seeds</td></tr><tr><td>7. Nigar Seed</td></tr><tr><td>8. Peanut kernel</td></tr><tr><td>9. Pongam seeds</td></tr><tr><td>10. Rapeseed</td></tr><tr><td>11. Sal Seed</td></tr><tr><td>12. Sesame seed</td></tr><tr><td>13. Soyabean</td></tr><tr><td>14. Sunflower seed</td></tr></tbody></table><br /><br />
                        </div>

                        <div style={{ position: "absolute", top: "60px", left: "430px" }}>
                                <table className="table table-border table-striped table-hover"><thead style={{ backgroundColor: "#232F3E", color: "white" }}><tr><th colspan="1">FRUITS</th></tr></thead><tbody><tr><td> 1. Amla</td></tr><tr><td>2. Apple</td></tr><tr><td>3. Apricot</td></tr><tr><td>4. Avocado</td></tr><tr><td>5. Banana </td></tr><tr><td>6. Ber</td></tr><tr><td>7. Bilimbi</td></tr><tr><td>8. Breadfruit</td></tr><tr><td>9. Cherry Red / Black</td></tr><tr><td>10. Custard apple</td></tr><tr><td>11. Garcinia</td></tr><tr><td>12. Grapefruit</td></tr><tr><td>13. Grapes </td></tr><tr><td>14. Guava</td></tr><tr><td>15. Jackfruit</td></tr><tr><td>16. Jamun</td></tr><tr><td>17. Kinnow</td></tr><tr><td>18. Lemon</td></tr><tr><td>19. Litchi</td></tr><tr><td>20. Mango</td></tr><tr><td>21. Mangosteen</td></tr><tr><td>22. Mootty Fruit</td></tr><tr><td>23. Musk melon</td></tr><tr><td>24. Orange</td></tr><tr><td>25. Papaya</td></tr><tr><td>26. Papaya Raw</td></tr><tr><td>27. Passion Fruit</td></tr><tr><td>28. Peach</td></tr><tr><td>29. Pear</td></tr><tr><td>30. Pineapple</td></tr><tr><td>31. Plum</td></tr><tr><td>32. Pomegranate</td></tr><tr><td>33. Rambutan</td></tr><tr><td>34. Raw Mango</td></tr><tr><td>35. Sapota</td></tr><tr><td>36. Soursop</td></tr><tr><td>37. Stawberries</td></tr><tr><td>38. Sweet orange</td></tr><tr><td>39. Watermelon</td></tr></tbody></table><br /><br />
                        </div>

                        <div style={{ position: "absolute", top: "60px", left: "625px" }}>
                                <table className="table table-border table-striped table-hover"><thead style={{ backgroundColor: "#232F3E", color: "white" }}><tr><th colspan="1">VEGETABLES</th></tr></thead><tbody><tr><td> 1. Aloe Vera</td></tr><tr><td>2. Arrowroot</td></tr><tr><td>3. Banana Raw</td></tr><tr><td>4. Beetroot</td></tr><tr><td>5. Bhindi/Okra</td></tr><tr><td>6. Bitter gourd</td></tr><tr><td>7. Bottle gourd</td></tr><tr><td>8. Brinjal</td></tr><tr><td>9. Broccoli/Calabrese</td></tr><tr><td>10. Button Mushroom</td></tr><tr><td>11. Cabbage</td></tr><tr><td>12. Capsicum</td></tr><tr><td>13. Carrots</td></tr><tr><td>14. Cauliflower</td></tr><tr><td>15. Cluster beans</td></tr><tr><td>16. Colocasia vegetable</td></tr><tr><td>17. Coriander leaves</td></tr><tr><td>18. Cucumber</td></tr><tr><td>19. Curry Leaves</td></tr><tr><td>20. Drumstick</td></tr><tr><td>21. Fenugreek Leaves </td></tr><tr><td>22. Garlic</td></tr><tr><td>23. Gherkin</td></tr><tr><td>24. Ginger</td></tr><tr><td>25. Green Amaranthus</td></tr><tr><td>26. Green chillies</td></tr><tr><td>27. Ivy gourd</td></tr><tr><td>28. Jimikand (Suran)</td></tr><tr><td>29. Lesser yam</td></tr><tr><td>30. Lobia Pods</td></tr><tr><td>31. Mint Leaves</td></tr><tr><td>32. Mustard leaf</td></tr><tr><td>33. Onion</td></tr><tr><td>34. Oyster Mushroom</td></tr><tr><td>35. Pea</td></tr><tr><td>36. Pointed gourd</td></tr><tr><td>37. Potato</td></tr><tr><td>38. Pumpkin</td></tr><tr><td>39. Raw Turmeric</td></tr><tr><td>40. Red Amaranthus</td></tr><tr><td>41. Reddish</td></tr><tr><td>42. Ribbed celery</td></tr><tr><td>43. Ridge Gourd</td></tr><tr><td>44. Round chilli</td></tr><tr><td>45. Safed Petha</td></tr><tr><td>46. Sem</td></tr><tr><td>47. Snake Guard</td></tr><tr><td>48. Spinach</td></tr><tr><td>49. Sponge Gourd</td></tr><tr><td>50. Spring Onion</td></tr><tr><td>51. Sugar Snap Peas</td></tr><tr><td>52. Sweet Corn</td></tr><tr><td>53. Sweet potato</td></tr><tr><td>54. Tapioca</td></tr><tr><td>55. Tinda</td></tr><tr><td>56. Tomato</td></tr><tr><td>57. Winged bean</td></tr></tbody></table><br /><br />
                        </div>

                        <div style={{ position: "absolute", top: "60px", left: "845px" }}>
                                <table className="table table-border table-striped table-hover"><thead style={{ backgroundColor: "#232F3E", color: "white" }}><tr><th colspan="1">SPICES</th></tr></thead><tbody><tr><td> 1. Ajwain</td></tr><tr><td>2. Black Pepper Whole</td></tr><tr><td>3. Cardamoms Whole</td></tr><tr><td>4. Cloves Whole</td></tr><tr><td>5. Coriander whole</td></tr><tr><td>6. Cumin</td></tr><tr><td>7. Dried Raw Mango Slices</td></tr><tr><td>8. Dry Ginger</td></tr><tr><td>9. Fennel seed</td></tr><tr><td>10. Fenugreek seed</td></tr><tr><td>11. Large cardamom</td></tr><tr><td>12. Mace Whole</td></tr><tr><td>13. Poppy Seed</td></tr><tr><td>14. Red chilli</td></tr><tr><td>15. Tejpata</td></tr><tr><td>16. Turmeric</td></tr></tbody></table><br /><br />
                        </div>

                        <div style={{ position: "absolute", top: "60px", left: "1085px",right:"10px" }}>
                                <table className="table table-border table-striped table-hover"><thead style={{ backgroundColor: "#232F3E", color: "white" }}><tr><th colspan="1">MISC</th></tr></thead><tbody><tr><td> 1. Anthurium</td></tr><tr><td>2. Areca nut (betel nut)</td></tr><tr><td>3. Bamboo</td></tr><tr><td>4. Betel leaves</td></tr><tr><td>5. Carnation</td></tr><tr><td>6. Chhappan Kaddu</td></tr><tr><td>7. Chironji</td></tr><tr><td>8. Chrysanthemum</td></tr><tr><td>9. Coconut</td></tr><tr><td>10. Coconut with Husk</td></tr><tr><td>11. Cotton</td></tr><tr><td>12. Gerbera</td></tr><tr><td>13. Ginger Seed</td></tr><tr><td>14. Gladiolus</td></tr><tr><td>15. Groundnut with pods</td></tr><tr><td>16. Guar seed</td></tr><tr><td>17. Hilsa</td></tr><tr><td>18. Isabgol </td></tr><tr><td>19. Jack Fruit Seed</td></tr><tr><td>20. Jaggery</td></tr><tr><td>21. Jute Seeds</td></tr><tr><td>22. Lily</td></tr><tr><td>23. Mahua flower</td></tr><tr><td>24. Mahua Seed</td></tr><tr><td>25. Marigold </td></tr><tr><td>26. Nutmeg Whole</td></tr><tr><td>27. Persimmon</td></tr><tr><td>28. Raisins</td></tr><tr><td>29. Raw Cashew nut</td></tr><tr><td>30. Raw Coffee Beans</td></tr><tr><td>31. Raw Jute</td></tr><tr><td>32. Rittha</td></tr><tr><td>33. Rose Cut Flower</td></tr><tr><td>34. Safed Musli</td></tr><tr><td>35. Saffron</td></tr><tr><td>36. Spray Chrysanthemum</td></tr><tr><td>37. Tamarind</td></tr><tr><td>38. Tender coconut</td></tr><tr><td>39. Tuberose</td></tr><tr><td>40. Tulip</td></tr><tr><td>41. Walnuts Inshell</td></tr></tbody></table><br /><br />
                        </div>
                        </div>
                </div>
        );
}

export default CommodityList;